# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Formatters
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: '.*/assets/rooms/configs/.*'
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-merge-conflict
      - id: check-case-conflict
        exclude: '\.pio/'

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '120']

  # Linters
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--config=flake8.ini]

  # Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
        - tomli

  # Cpp files formatter
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        args: [-style=file]
        files: '\.cpp$|\.hpp$'  # Run on .cpp and .hpp files
        exclude: '\.pio/'

  # Python files formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Make sure to use the correct version
    hooks:
      - id: black
        args: ['--line-length', '120', "--unstable"]
        files: '\.py$'  # Ensure black runs only on Python files

  # Jupyter notebook strip outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
    - id: nbstripout
